### ISSUE TITLE
Task: speech-enhancement peer review and testing

### ISSUE THREAD

**Issue by ibevers** [sensein/senselab#104]
### Description

Review and test speech-enhancement

### Tasks

- [x] Review
- [x] Test

**Comment by ibevers** [comment]
This looks pretty good. I implemented some to-dos that were left in the docstring. I'm wondering if we should use a similar factory in other tasks where we are getting a large model to improve performance.

**Comment by fabiocat93** [comment]
Thank you, @ibevers. Currently, the factory only functions as expected when the code runs sequentially. If we attempt to parallelize it using Pydra, each process will have its own instance of the factory. This causes us to lose the optimized behavior we were aiming for. I am experimenting with different solutions to address this issue, but I haven't found one that fully convinces me yet. if you happen to have ideas about this, please feel free to share

**Comment by ibevers** [comment]
@fabiocat93 I've been thinking about this a bit, and I'm wondering if we could create a shared enhancer object that uses the same model using `multiprocessing.Manager` and update the API to accept it as a parameter. I went ahead and updated the API (easy to change it back, and it doesn't affect existing usage). I got ChatGPT to generate this example:
```
if __name__ == "__main__":
    # Initialize Manager and shared SpeechBrainEnhancer
    with Manager() as manager:
        shared_enhancer = manager.SpeechBrainEnhancer()

        # List of audio inputs
        audio_inputs = [Audio(waveform=torch.randn(1, 16000), sampling_rate=16000) for _ in range(10)]

        # Create a Pydra task for enhancing audio
        enhance_task = enhance_audio_chunk(shared_enhancer=shared_enhancer, audio_chunk=audio_inputs)
        enhance_task.split("audio_chunk", audio_inputs, n_splits=5)

        # Create and run the workflow
        wf = Workflow(name="enhance_workflow", input_spec=["audio_inputs"], audio_inputs=audio_inputs)
        wf.add(enhance_task)
        wf.set_output([("enhanced_audios", enhance_task.lzout)])

        with pydra.Submitter(plugin="cf") as sub:
            sub(wf)

        # Collect and print the results
        enhanced_audios = wf.result()
        print("Enhanced audios:", enhanced_audios)
```
I'm not sure if pydra can be run `with Manager()`.

**Comment by ibevers** [comment]
If so, then we could either wrap code like the above in the API or provide instructions for running with `Manager`.

**Comment by ibevers** [comment]
Working on getting a minimal working example with this approach...

**Comment by ibevers** [comment]
With this code:
```
def enhance_audios(
    audios: List[Audio],
    model: SenselabModel = SpeechBrainModel(path_or_uri="speechbrain/sepformer-wham16k-enhancement", revision="main"),
    enhancer: Optional[ValueProxy] = None,
    device: Optional[DeviceType] = None,
) -> List[Audio]:
    """Enhances all audios using the given model.

    Args:
        audios (List[Audio]): The list of audio objects to be enhanced.
        model (SenselabModel): The model used for enhancement
            (default is "speechbrain/sepformer-wham16k-enhancement").
        enhancer (SpeechBrainEnhancer, optional): The enhancer instance to use for enhancement.
            If not provided, the default SpeechBrainEnhancer will be used if the model is a SpeechBrainModel.
        device (Optional[DeviceType]): The device to run the model on (default is None).

    Returns:
        List[Audio]: The list of enhanced audio objects.

    Raises:
        NotImplementedError: If the model is not an instance of SpeechBrainModel and no enhancer is provided.
    """
    if enhancer and isinstance(model, SpeechBrainModel):
        return enhancer.value.enhance_audios_with_speechbrain(audios=audios, model=model, device=device)
    elif isinstance(model, SpeechBrainModel):
        return SpeechBrainEnhancer.enhance_audios_with_speechbrain(audios=audios, model=model, device=device)
    else:
        raise NotImplementedError("Only SpeechBrain models are supported for now.")
```
and 

```

if __name__ == "__main__":
    # Initialize Manager and shared SpeechBrainEnhancer
    with Manager() as manager:
        shared_enhancer = manager.Value(SpeechBrainEnhancer, SpeechBrainEnhancer())

        # List of audio inputs
        audio_inputs = [[Audio(waveform=torch.randn(1, 16000), sampling_rate=16000) for _ in range(3)]]

        # Create and run the workflow
        wf = Workflow(name="enhance_workflow", input_spec=["audio_inputs"])

        # setting a plitter for the entire workflow
        wf.split('audio_inputs', audio_inputs=audio_inputs)

        wf.add(enhance_audios_pt(name="enhance_task",
            audios=wf.lzin.audio_inputs, 
            enhancer=[shared_enhancer]
        ))

        # Set the workflow output
        wf.set_output([("enhanced_audios", wf.enhance_task.lzout.out)])

        # Run the workflow
        with pydra.Submitter(plugin="cf") as sub:
            sub(wf)

        # Collect and print the results
        enhanced_audios = wf.result().output.enhanced_audios
        print("Enhanced audios:", enhanced_audios)
 ```

I get 
```
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/Users/isaacbevers/Library/Caches/pypoetry/virtualenvs/senselab-_dRIpWVy-py3.10/lib/python3.10/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/isaacbevers/sensein/senselab-wrapper/test_manager_with_pydra_speech_enhancement.py", line 47, in <module>
    wf.add(enhance_audios_pt(name="enhance_task",
  File "/Users/isaacbevers/Library/Caches/pypoetry/virtualenvs/senselab-_dRIpWVy-py3.10/lib/python3.10/site-packages/pydra/mark/functions.py", line 47, in decorate
    return FunctionTask(func=func, **kwargs)
  File "/Users/isaacbevers/Library/Caches/pypoetry/virtualenvs/senselab-_dRIpWVy-py3.10/lib/python3.10/site-packages/pydra/engine/task.py", line 155, in __init__
    super().__init__(
  File "/Users/isaacbevers/Library/Caches/pypoetry/virtualenvs/senselab-_dRIpWVy-py3.10/lib/python3.10/site-packages/pydra/engine/core.py", line 176, in __init__
    self.inputs = attr.evolve(self.inputs, **inputs)
  File "/Users/isaacbevers/Library/Caches/pypoetry/virtualenvs/senselab-_dRIpWVy-py3.10/lib/python3.10/site-packages/attr/_funcs.py", line 419, in evolve
    return cls(**changes)
  File "<attrs generated init pydra.engine.helpers.Inputs-1>", line 5, in __init__
  File "/Users/isaacbevers/Library/Caches/pypoetry/virtualenvs/senselab-_dRIpWVy-py3.10/lib/python3.10/site-packages/pydra/utils/typing.py", line 197, in __call__
    coerced = self.coerce(obj)
  File "/Users/isaacbevers/Library/Caches/pypoetry/virtualenvs/senselab-_dRIpWVy-py3.10/lib/python3.10/site-packages/pydra/utils/typing.py", line 340, in coerce
    return expand_and_coerce(object_, self.pattern)
  File "/Users/isaacbevers/Library/Caches/pypoetry/virtualenvs/senselab-_dRIpWVy-py3.10/lib/python3.10/site-packages/pydra/utils/typing.py", line 213, in expand_and_coerce
    return coerce_union(obj, pattern_args)
  File "/Users/isaacbevers/Library/Caches/pypoetry/virtualenvs/senselab-_dRIpWVy-py3.10/lib/python3.10/site-packages/pydra/utils/typing.py", line 258, in coerce_union
    raise TypeError(
TypeError: Could not coerce object, [<ValueProxy object, typeid 'Value' at 0x14a163c40>], to any of the union types [<class 'multiprocessing.managers.ValueProxy'>, <class 'NoneType'>] in 'enhancer' field of Inputs :

<class 'multiprocessing.managers.ValueProxy'> -> Cannot coerce [<ValueProxy object, typeid 'Value' at 0x14a163c40>] into <class 'multiprocessing.managers.ValueProxy'> in 'enhancer' field of Inputs  as the coercion doesn't match any of the explicit inclusion criteria: Sequence -> Sequence, Mapping -> Mapping, Path -> PathLike, str -> PathLike, PathLike -> Path, PathLike -> str, Any -> MultiInputObj, int -> float, Integer -> float, int -> Decimal, Boolean -> bool, Decimal -> float, Integer -> int, Text -> str, bool -> Boolean, float -> Decimal, int -> Integer, str -> Text, integer -> int, floating -> float, bool_ -> bool, integer -> float, character -> str, complexfloating -> complex, bytes_ -> bytes, ndarray -> Sequence, Sequence -> ndarray

<class 'NoneType'> -> Cannot coerce [<ValueProxy object, typeid 'Value' at 0x14a163c40>] into <class 'NoneType'> in 'enhancer' field of Inputs  as the coercion doesn't match any of the explicit inclusion criteria: Sequence -> Sequence, Mapping -> Mapping, Path -> PathLike, str -> PathLike, PathLike -> Path, PathLike -> str, Any -> MultiInputObj, int -> float, Integer -> float, int -> Decimal, Boolean -> bool, Decimal -> float, Integer -> int, Text -> str, bool -> Boolean, float -> Decimal, int -> Integer, str -> Text, integer -> int, floating -> float, bool_ -> bool, integer -> float, character -> str, complexfloating -> complex, bytes_ -> bytes, ndarray -> Sequence, Sequence -> ndarray
```

**Comment by ibevers** [comment]
I tried 
```
@register_serializer(ValueProxy)
def bytes_repr_valueproxy(obj: ValueProxy, cache) -> Iterator[bytes]:
    # Serialize the type and value inside the ValueProxy
    yield b"ValueProxy:{"
    yield from bytes_repr(obj.value, cache)
    yield b"}"
```

**Comment by ibevers** [comment]
That didn't work, but registering a serializer somewhat differently still might.

**Comment by fabiocat93** [comment]
thank you @ibevers . i find your approach interesting. why not using pydra under the hood in `enhance_audios_with_speechbrain`? we can still ask the user to choose the plugin (e.g., `serial`, `cf`), but we don't need to expose the factory/factory manager. what do you think?

**Comment by ibevers** [comment]
I completely agree assuming we can get the serializer working.

**Comment by ibevers** [comment]
> @fabiocat93 I've been thinking about this a bit, and I'm wondering if we could create a shared enhancer object that uses the same model using `multiprocessing.Manager` and update the API to accept it as a parameter. I went ahead and updated the API (easy to change it back, and it doesn't affect existing usage).

@fabiocat93 I think this would still ideally take the enhancer as a parameter because we might eventually have workflows that use a speech enhancement task in multiple sub-workflows, and we won't want each of them to create a new `SpeechBrainEnhancer`.
