### ISSUE TITLE
Support: Pytest Squim Issue Locally

### ISSUE THREAD

**Issue by ibevers** [sensein/senselab#225]
### Issue Description

<img width="915" alt="Screenshot 2024-12-18 at 3 38 53 PM" src="https://github.com/user-attachments/assets/aba0f6be-aa80-40ce-9ea4-0fa926372ebd" />

### Environment Details

MacOS, Python3.12

### Attempted Solutions

`poetry cache clear --all pypi`
`poetry update`

### Reproduction Steps
Run `poetry run pytest`

**Comment by ibevers** [comment]
Here is what happens when I install a clean senselab and run tests:
https://gist.githubusercontent.com/ibevers/6a8aacf3b2be2ef362f836cbf5c27607/raw/20b8762e87edde71a88cb98e438c74626aeed8e5/gistfile1.txt
<img width="1000" alt="Screenshot 2024-12-18 at 4 41 50 PM" src="https://github.com/user-attachments/assets/73f0a8e3-e896-401a-b8d5-70bb9affd5e3" />

**Comment by fabiocat93** [comment]
Thank you @ibevers for bringing up this issue! This was already discussed internally (Slack) yesterday, and maybe you found a solution already.  If not, I would recommend trying the following steps to address the problem:

1. Install with Poetry without cache:
`poetry install --no-cache --with dev`

2. Debug with a smaller test so that you isolate the problematic function:

```
from torchaudio.pipelines import SQUIM_SUBJECTIVE
model = SQUIM_SUBJECTIVE.get_model()
```

**Comment by ibevers** [comment]
@fabiocat93 Thanks, I will try that:)

**Comment by fabiocat93** [comment]
hi @ibevers , is this still an open issue for you? How did your isolated experiment with SQUIM_SUBJECTIVE go?

**Comment by ibevers** [comment]
@fabiocat93 doesn't work:
```
>>> from torchaudio.pipelines import SQUIM_SUBJECTIVE
model = SQUIM_SUBJECTIVE.get_model()>>> model = SQUIM_SUBJECTIVE.get_model()
squim_subjective_bvcc_daps.pth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/isaacbevers/Library/Caches/pypoetry/virtualenvs/senselab-_dRIpWVy-py3.12/lib/python3.12/site-packages/torchaudio/pipelines/_squim_pipeline.py", line 130, in get_model
    state_dict = torch.load(path, weights_only=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isaacbevers/Library/Caches/pypoetry/virtualenvs/senselab-_dRIpWVy-py3.12/lib/python3.12/site-packages/torch/serialization.py", line 1326, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/isaacbevers/Library/Caches/pypoetry/virtualenvs/senselab-_dRIpWVy-py3.12/lib/python3.12/site-packages/torch/serialization.py", line 671, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by ibevers** [comment]
@fabiocat93 Still open

**Comment by fabiocat93** [comment]
> @fabiocat93 doesn't work:
> 
> ```
> >>> from torchaudio.pipelines import SQUIM_SUBJECTIVE
> model = SQUIM_SUBJECTIVE.get_model()>>> model = SQUIM_SUBJECTIVE.get_model()
> squim_subjective_bvcc_daps.pth
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/isaacbevers/Library/Caches/pypoetry/virtualenvs/senselab-_dRIpWVy-py3.12/lib/python3.12/site-packages/torchaudio/pipelines/_squim_pipeline.py", line 130, in get_model
>     state_dict = torch.load(path, weights_only=True)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/isaacbevers/Library/Caches/pypoetry/virtualenvs/senselab-_dRIpWVy-py3.12/lib/python3.12/site-packages/torch/serialization.py", line 1326, in load
>     with _open_zipfile_reader(opened_file) as opened_zipfile:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/isaacbevers/Library/Caches/pypoetry/virtualenvs/senselab-_dRIpWVy-py3.12/lib/python3.12/site-packages/torch/serialization.py", line 671, in __init__
>     super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
> ```

This suggests that the issue isn’t with `senselab` itself, which makes sense since others aren’t encountering it. The focus now is on understanding what might be causing it in your case

**Comment by ibevers** [comment]
@fabiocat93 I think the model files might have been corrupted since this fixed it:
`rm -rf ~/.cache/torch/hub/torchaudio/models/*`

Thank you for your support!
